### ISSUE TITLE
Unusually high infection rates when known infections added to sampler

### ISSUE THREAD

**Issue by dchodge** [seroanalytics/serojump#5]
When running wave2 (delta) analysis on TRANSVIR the posteriors are estimating ~98% exposure rates, which is unusually high. I think this is either i) due to an internal issue with the reversible jump jacobian needing to be altered to account for know infection, or ii) maybe the kinetics are not quite correct and need titre-dependent boosting. Will explore further

**Comment by adamkucharski** [comment]
What does the sampler estimate for those infections when they aren't included as known? I.e. are they are mostly inferred – in which case, surprising that the estimation would change much, as fixing them should just be equivalent of starting MCMC in higher likelihood region?

**Comment by dchodge** [comment]
This has now been fixed; there was an issue with the internal likelihood which meant that boosting was attenuated for those infected making causing identifiability issues between those infected and not infected.
